name = "GRNEvoContingencyAnalysis"
authors = ["Harry Booth"]

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
BetaML = "024491cd-cc6b-443e-8034-08ea7eb7db2b"
BifurcationKit = "0f109fa4-8a5d-4b75-95aa-f515264e7665"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
ClusterManagers = "34f1f09b-3a8b-5176-ab39-66d58a4d544e"
ClusterValidityIndices = "2fefd308-f647-4698-a2f0-e90cfcbca9ad"
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"
DecisionTree = "7806a523-6efd-50cb-b5f6-3fa6f1930dbb"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
DistributedArrays = "aaf54ef3-cdf8-58ed-94cc-d582ad619b94"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
DynamicAxisWarping = "aaaaaaaa-4a10-5553-b683-e707b00e83ce"
EvoTrees = "f6006082-12f8-11e9-0c9c-0d5d367ab1e5"
GLPK = "60bf3e95-4087-53dc-ae20-288a0d20c6a6"
Gen = "ea4f424c-a589-11e8-07c0-fd5c91b9da4a"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
GraphMakie = "1ecd5474-83a3-4783-bb4f-06765db800d2"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
ImageMagick = "6218d12a-5da1-5696-b52f-db25d2ecc6d1"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
LayeredLayouts = "f4a74d36-062a-4d48-97cd-1356bad1de4e"
LazySets = "b4f0291d-fe17-52bc-9479-3d1a343d9043"
LogExpFunctions = "2ab3a3ac-af41-5b50-aa03-7779005ae688"
MLDataPattern = "9920b226-0b2a-5f5f-9153-9aa70a013f8b"
MLDatasets = "eb30cadb-4394-5ae3-aed4-317e484a6458"
MLJ = "add582a8-e3ab-11e8-2d5e-e98b27df1bc7"
MLJDecisionTreeInterface = "c6f25543-311c-4c74-83dc-3ea6d1015661"
Measures = "442fdcdd-2543-5da2-b0f3-8c86c306513e"
Memoization = "6fafb56a-5788-4b4e-91ca-c0cea6611c73"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
MultipleTesting = "f8716d33-7c4a-5097-896f-ce0ecbd3ef6b"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
NetworkLayout = "46757867-2c16-5918-afeb-47bfcb05e46a"
OnlineStats = "a15396b6-48d5-5d58-9928-6d29437db91e"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationPolyalgorithms = "500b13db-7e66-49ce-bda4-eed966be6282"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Polyhedra = "67491407-f73d-577b-9b50-8179a7c68029"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
PyCallJLD2 = "07b0ad8c-101f-43fe-82b6-eff101a491e1"
SciMLSensitivity = "1ed8b502-d754-442c-8d5d-10ac956f44a1"
ScikitLearn = "3646fa90-6ef7-5e7e-9f22-8aca16db6324"
ShapML = "8523bd24-6f66-414b-9e1e-b02db3916d64"
Shapley = "855ca7ad-a6ef-4de2-9ca8-726fe2a39065"
SharedArrays = "1a1011a3-84de-559e-8e89-a11a2f7dc383"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
TSne = "24678dba-d5e9-5843-a4c6-250288b04835"
UMAP = "c4f8c510-2410-5be4-91d7-4fbaeb39457e"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
DrWatson = "2.9.1"
julia = "1.8.2"
